workflows:
  android-apk:
    name: Android APK
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - gradle wrapper --gradle-version 8.7
      - chmod +x gradlew
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
